Repository GSG-G11/CleanStead, pull requests merged in 2022-04, with the labels that each got.

#6 Create file structure
  .eslintrc.json
  .gitignore
  .vscode/settings.json
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App/app.css
  client/src/App/index.js
  client/src/Components/index.js
  client/src/Pages/index.js
  client/src/Utils/index.js
  client/src/index.js
  package-lock.json
  package.json
  server/app.ts
  server/controllers/errorHandle/index.ts
  server/controllers/index.ts
  server/controllers/middlewares/auth/index.ts
  server/database/build.sql
  server/database/build.ts
  server/database/connection.ts
  server/database/fakeData.sql
  server/index.ts
  server/queries/index.ts
  server/utils/index.ts
  server/validation/index.ts
Labels: Awaiting Review

#8 project setup
  .eslintrc.json
  .vscode/settings.json
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App/index.js
  client/src/App/index.jsx
  client/src/index.jsx
  package-lock.json
  package.json
  server/app.ts
  server/index.ts
  test/index.test.ts
  tsconfig.json
Labels: Backend, Approved

#17 database configs
  .gitignore
  .vscode/settings.json
  client/package-lock.json
  package-lock.json
  package.json
  server/database/build.ts
  server/database/connection.ts
Labels: Awaiting Review

#31 custom title component
  client/src/Components/Custom Title/index.jsx
  client/src/Components/Custom Title/style.css
  client/src/Components/index.js
  client/src/assets/images/linesLeft.svg
  client/src/assets/images/linesRight.svg
Labels: Awaiting Review

#15 create database schema and fake data
  server/database/build.sql
  server/database/config.sql
  server/database/fakeData.sql
Labels: Awaiting Review

#37 get categories
  .github/workflows/node.js.yml
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
  server/app.ts
  server/controllers/categories/getCategories.ts
  server/controllers/categories/index.ts
  server/controllers/index.ts
  server/database/build.ts
  server/database/connection.ts
  server/queries/categories/getCategoriesQuery.ts
  server/queries/categories/index.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Approved

#32 Create header component
  .gitignore
  .vscode/settings.json
  client/package-lock.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App/index.jsx
  client/src/Assets/images/headerBackground.svg
  client/src/Components/CustomTitle/index.jsx
  client/src/Components/CustomTitle/style.css
  client/src/Components/Header/index.jsx
  client/src/Components/Header/style.css
  client/src/Components/index.js
  client/src/Components/index.jsx
Labels: Approved
