Repository GSG-G11/CleanStead, pull requests merged in 2022-05, with the labels that each got.

#34 create navbar compnent
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App/app.css
  client/src/App/index.jsx
  client/src/Components/CustomTitle/index.jsx
  client/src/Components/Header/index.jsx
  client/src/Components/Navbar/LeftMenu.jsx
  client/src/Components/Navbar/RightMenu.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/Navbar/navbar.css
  client/src/Components/index.jsx
  client/src/assets/images/logo.svg
  client/src/index.jsx
  client/src/style/custom-antd.css
Labels: Done

#42 get services for each category from database
  client/package-lock.json
  server/controllers/categories/getCategoryServices.ts
  server/controllers/categories/index.ts
  server/controllers/index.ts
  server/database/config.sql
  server/database/fakeData.sql
  server/queries/categories/getCategoryServicesQuery.ts
  server/queries/categories/index.ts
  server/queries/index.ts
  server/routes/index.ts
  server/validation/categroyIdSchema.ts
  server/validation/index.ts
  test/index.test.ts
Labels: Approved

#44 categories cards container
  client/src/App/index.jsx
  client/src/Components/CategoriesCard/style.css
  client/src/Components/CategoriesCardsContainer/index.jsx
  client/src/Components/CategoriesCardsContainer/style.css
  client/src/Components/Empty/index.jsx
  client/src/Components/SkeletonLoading/index.jsx
  client/src/Components/index.jsx
  client/src/Pages/Home/index.jsx
  client/src/style/custom-antd.css
Labels: Done, Approved

#33 Why us
  client/src/App/index.jsx
  client/src/Assets/images/Reservation.png
  client/src/Assets/images/discounts.png
  client/src/Assets/images/img.png
  client/src/Assets/images/linesLeft.svg
  client/src/Assets/images/linesRight.svg
  client/src/Assets/images/reliability.png
  client/src/Assets/images/support.png
  client/src/Components/CustomTitle/index.jsx
  client/src/Components/Navbar/LeftMenu.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/WhyUs/WhyUs.css
  client/src/Components/WhyUs/index.jsx
  client/src/Components/index.jsx
  client/src/Pages/Home/index.jsx
  client/src/Pages/index.jsx
  client/src/assets/images/logo.svg
  client/src/style/custom-antd.css
Labels: Done, Approved

#49 get contact
  server/controllers/contact/getContacts.ts
  server/controllers/contact/index.ts
  server/controllers/index.ts
  server/database/build.sql
  server/database/fakeData.sql
  server/queries/contact/getContactsQuery.ts
  server/queries/contact/index.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Backend, Approved

#46 create service component and details page
  client/package-lock.json
  client/package.json
  client/src/App/index.jsx
  client/src/Components/CategoriesCardsContainer/index.jsx
  client/src/Components/CategoryServices/ServiceCard.jsx
  client/src/Components/CategoryServices/Services.jsx
  client/src/Components/CategoryServices/ServicesLoading.jsx
  client/src/Components/CategoryServices/style.css
  client/src/Components/Empty/index.jsx
  client/src/Components/Footer/style.css
  client/src/Components/SkeletonLoading/index.jsx
  client/src/Pages/Category/index.jsx
  server/database/fakeData.sql
  server/queries/categories/getCategoryServicesQuery.ts
Labels: Awaiting Review, Frontend

#54 register
  server/controllers/index.ts
  server/controllers/signup/index.ts
  server/database/build.sql
  server/queries/index.ts
  server/queries/user/addUserQuery.ts
  server/queries/user/checkEmailExistsQuery.ts
  server/queries/user/index.ts
  server/routes/index.ts
  server/validation/index.ts
  server/validation/signupSchema.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Priority - 0

#58 login
  server/controllers/index.ts
  server/controllers/signin/index.ts
  server/queries/user/checkEmailExistsQuery.ts
  server/routes/index.ts
  server/validation/index.ts
  server/validation/signinSchema.ts
  server/validation/signupSchema.ts
  test/index.test.ts
Labels: Backend, Approved

#55 what they say
  client/package-lock.json
  client/src/App/app.css
  client/src/App/index.jsx
  client/src/Assets/icons/quote.svg
  client/src/Components/CategoryServices/style.css
  client/src/Components/Footer/index.jsx
  client/src/Components/Navbar/navbar.css
  client/src/Components/QuoteCard/index.jsx
  client/src/Components/QuoteCard/style.css
  client/src/Components/WhatTheySay/index.jsx
  client/src/Components/WhatTheySay/style.css
  client/src/Components/WhyUs/index.jsx
  client/src/Components/index.jsx
  client/src/Pages/Home/index.jsx
  client/src/Pages/index.jsx
  client/src/Quotes.json
  client/src/index.jsx
  package-lock.json
Labels: Awaiting Review

#65 add custom title
  client/src/Components/WhyUs/index.jsx
Labels: Awaiting Review

#41 create description card
  client/src/App/index.jsx
  client/src/Assets/images/img1.png
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/ContactUsForm/style.css
  client/src/Components/CustomTitle/style.css
  client/src/Components/DescriptionContent/index.jsx
  client/src/Components/DescriptionContent/style.css
  client/src/Components/index.jsx
  client/src/Pages/Description/index.jsx
  client/src/Pages/index.jsx
  client/src/style/custom-antd.css
  package-lock.json
Labels: Awaiting Review

#59 logout check auth
  server/controllers/categories/getCategoryServices.ts
  server/controllers/contact/addContact.ts
  server/controllers/index.ts
  server/controllers/logout/index.ts
  server/controllers/middlewares/auth/index.ts
  server/controllers/signin/index.ts
  server/controllers/signup/index.ts
  server/routes/index.ts
  server/utils/error/index.ts
  server/utils/index.ts
  server/utils/jwt/index.ts
  server/utils/jwt/jwtSign.ts
  server/utils/jwt/jwtVerify.ts
Labels: Backend, Approved

#66 Post api/v1/services
  .eslintrc.json
  server/controllers/index.ts
  server/controllers/services/index.ts
  server/controllers/services/postService.ts
  server/queries/index.ts
  server/queries/services/index.ts
  server/queries/services/postServiceQuery.ts
  server/routes/index.ts
  server/validation/index.ts
  server/validation/servicesSchema.ts
  test/index.test.ts
Labels: Awaiting Review, Backend

#67 add admins table
  server/database/build.sql
  server/database/fakeData.sql
Labels: Awaiting Review

#68 handle get books
  server/controllers/book/getBooks.ts
  server/controllers/book/index.ts
  server/controllers/index.ts
  server/queries/book/getBooksQuery.ts
  server/queries/book/index.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review

#50 login register component
  client/package-lock.json
  client/src/App/index.jsx
  client/src/Components/CategoriesCard/style.css
  client/src/Components/CategoriesCardsContainer/index.jsx
  client/src/Components/CategoriesCardsContainer/style.css
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/Login/index.jsx
  client/src/Components/LoginRegisterContainer/index.jsx
  client/src/Components/LoginRegisterContainer/style.css
  client/src/Components/Navbar/RightMenu.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/Register/index.jsx
  client/src/Components/index.jsx
  client/src/style/custom-antd.css
  server/controllers/signin/index.ts
  server/validation/signupSchema.ts
  test/index.test.ts
Labels: Awaiting Review, Frontend

#70 edit description content
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/DescriptionContent/index.jsx
  client/src/Components/DescriptionContent/style.css
Labels: Frontend, Approved

#73 get specifc book
  server/controllers/book/getBook.ts
  server/controllers/book/getUserBooks.ts
  server/controllers/book/index.ts
  server/controllers/index.ts
  server/controllers/middlewares/index.ts
  server/controllers/middlewares/validateLink.ts
  server/queries/book/getBookQuery.ts
  server/queries/book/getUserBooksQuery.ts
  server/queries/book/index.ts
  server/queries/index.ts
  server/routes/index.ts
  server/validation/index.ts
  server/validation/paramsIdSchema.ts
  test/index.test.ts
Labels: Awaiting Review

#77 handle contact us form with server
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/ContactUsForm/style.css
  server/controllers/contact/addContact.ts
  server/queries/contact/addContactQuery.ts
  server/validation/contactSchema.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Frontend

#72 post categories
  server/controllers/categories/index.ts
  server/controllers/categories/postCategories.ts
  server/controllers/index.ts
  server/controllers/middlewares/validateLink.ts
  server/queries/categories/index.ts
  server/queries/categories/postCategoriesQuery.ts
  server/queries/index.ts
  server/routes/index.ts
  server/utils/jwt/index.ts
  server/validation/categoriesSchema.ts
  server/validation/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend

#71 DELETE api/v1/services/:id
  server/controllers/categories/getCategoryServices.ts
  server/controllers/index.ts
  server/controllers/middlewares/auth/checkAdmin.ts
  server/controllers/middlewares/auth/checkAuth.ts
  server/controllers/middlewares/auth/index.ts
  server/controllers/services/deleteService.ts
  server/controllers/services/index.ts
  server/database/build.sql
  server/queries/index.ts
  server/queries/services/deleteServiceQuery.ts
  server/queries/services/index.ts
  server/routes/index.ts
  server/validation/categroyIdSchema.ts
  server/validation/index.ts
  server/validation/paramsIdSchema.ts
  test/index.test.ts
Labels: Backend, Approved

#79 PUT api/v1/services/:id
  server/controllers/index.ts
  server/controllers/services/index.ts
  server/controllers/services/putService.ts
  server/queries/index.ts
  server/queries/services/index.ts
  server/queries/services/putServiceQuery.ts
  server/routes/index.ts
  server/validation/paramsIdSchema.ts
  test/index.test.ts
Labels: Backend, Approved

#87 edit database
  client/src/cities.json
  server/database/build.sql
  server/database/fakeData.sql
  server/queries/book/getBookQuery.ts
  server/queries/book/getBooksQuery.ts
  server/queries/book/getUserBooksQuery.ts
Labels: Done

#75 dashborad-container
  client/src/App/index.jsx
  client/src/Assets/images/user.png
  client/src/Components/Dashboard/Book/index.jsx
  client/src/Components/Dashboard/Categories/index.jsx
  client/src/Components/Dashboard/Contact/index.jsx
  client/src/Components/Dashboard/General/index.jsx
  client/src/Components/Dashboard/LoginAdmin/index.jsx
  client/src/Components/Dashboard/Services/index.jsx
  client/src/Components/Dashboard/index.jsx
  client/src/Components/Layout/index.jsx
  client/src/Components/index.jsx
  client/src/Pages/Dashboard/index.jsx
  client/src/Pages/Dashboard/style.css
  client/src/Pages/index.jsx
  client/src/index.jsx
Labels: Awaiting Review, Frontend

#60 book container
  client/package-lock.json
  client/package.json
  client/src/App/index.jsx
  client/src/Components/BookNow/BookContainer.jsx
  client/src/Components/BookNow/CompleteBook.jsx
  client/src/Components/BookNow/DateTimeChoice.jsx
  client/src/Components/BookNow/ServicesChoice.jsx
  client/src/Components/BookNow/ServicesCollapse.jsx
  client/src/Components/BookNow/Summary.jsx
  client/src/Components/BookNow/UserInformation.jsx
  client/src/Components/BookNow/style.css
  client/src/Components/LoginRegisterContainer/index.jsx
  client/src/Components/LoginRegisterContainer/style.css
  client/src/Pages/Book/index.jsx
  client/src/Pages/index.jsx
  client/src/style/custom-antd.css
  server/controllers/book/updateBook.ts
  server/queries/book/updateBookQuery.ts
  server/validation/bookSchema.ts
Labels: Awaiting Review, Frontend

#88 POST api/v1/book
  client/package-lock.json
  server/controllers/book/index.ts
  server/controllers/book/postBook.ts
  server/controllers/index.ts
  server/database/build.sql
  server/database/fakeData.sql
  server/queries/book/index.ts
  server/queries/book/postBookQuery.ts
  server/queries/index.ts
  server/routes/index.ts
  server/validation/bookSchema.ts
  server/validation/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend

#90 edit input location from text to select at register
  client/src/Components/Register/index.jsx
  server/controllers/signup/index.ts
  server/queries/user/addUserQuery.ts
  server/validation/signupSchema.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Frontend, Priority - 0

#99 UserInfo Context
  client/package-lock.json
  client/package.json
  client/src/Components/Layout/index.jsx
  client/src/Components/Login/index.jsx
  client/src/Components/LoginRegisterContainer/index.jsx
  client/src/Components/Navbar/RightMenu.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/Register/index.jsx
  client/src/context/userContext.jsx
  package-lock.json
  server/controllers/signin/index.ts
  server/controllers/signup/index.ts
  server/queries/user/checkEmailExistsQuery.ts
Labels: Awaiting Review, Frontend, Priority - 0

#96 add categories context
  client/src/App/index.jsx
  client/src/Components/CategoriesCardsContainer/index.jsx
  client/src/Components/CategoryServices/Services.jsx
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/DescriptionContent/index.jsx
  client/src/Components/Footer/index.jsx
  client/src/Components/Layout/index.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Contexts/CategoriesContext.jsx
  client/src/Pages/Category/index.jsx
  client/src/Pages/Description/index.jsx
  client/src/Pages/Home/index.jsx
Labels: Awaiting Review, Priority - 0

#94 add context for open modal login and logged user
  client/src/Components/BookNow/BookContainer.jsx
  client/src/Components/BookNow/ServicesChoice.jsx
  client/src/Components/BookNow/UserInformation.jsx
  client/src/Components/Layout/index.jsx
  client/src/Components/Login/index.jsx
  client/src/Components/LoginRegisterContainer/index.jsx
  client/src/Components/Navbar/RightMenu.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/Register/index.jsx
  client/src/Contexts/ModalLogin.jsx
  client/src/Contexts/userContext.jsx
  client/src/Pages/Book/index.jsx
  server/controllers/signin/index.ts
  server/controllers/signup/index.ts
  server/queries/user/addUserQuery.ts
  server/queries/user/checkEmailExistsQuery.ts
  server/validation/signupSchema.ts
Labels: Awaiting Review, Priority - 1

#110 404 Not Found Page
  client/src/App/index.jsx
  client/src/Assets/images/notfoundimage.png
  client/src/Pages/NotFound/index.jsx
  client/src/Pages/NotFound/style.css
  client/src/Pages/index.jsx
Labels: Awaiting Review, Frontend

#78 handle achieved category
  server/controllers/categories/archivedCategories.ts
  server/controllers/categories/index.ts
  server/controllers/index.ts
  server/queries/categories/archivedCategoriesQuery.ts
  server/queries/categories/getCategoriesQuery.ts
  server/queries/categories/index.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Priority - 2

#107 add status book
  server/controllers/book/getStatus.ts
  server/controllers/book/index.ts
  server/controllers/index.ts
  server/database/build.sql
  server/database/fakeData.sql
  server/queries/book/getStatusQuery.ts
  server/queries/book/index.ts
  server/queries/book/postBookQuery.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Priority - 2

#98 handle archived services
  server/controllers/index.ts
  server/controllers/services/archivedService.ts
  server/controllers/services/deleteService.ts
  server/controllers/services/index.ts
  server/queries/index.ts
  server/queries/services/archivedServiceQuery.ts
  server/queries/services/deleteServiceQuery.ts
  server/queries/services/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Priority - 2

#102 add admin component
  client/src/App/index.jsx
  client/src/Components/Dashboard/AdminLogin/index.jsx
  client/src/Components/Dashboard/AdminLogin/style.css
  client/src/Components/Dashboard/LoginAdmin/index.jsx
  client/src/Components/Dashboard/index.jsx
  client/src/Components/Layout/index.jsx
  client/src/Components/Login/index.jsx
  client/src/Components/index.jsx
  client/src/Contexts/adminContext.jsx
  client/src/Pages/Dashboard/index.jsx
  server/controllers/index.ts
  server/controllers/logout/index.ts
  server/controllers/signinAdmin/index.ts
  server/queries/admin/index.ts
  server/routes/index.ts
Labels: Awaiting Review, Frontend, Priority - 0

#113 protected dashboard routes
  client/src/App/index.jsx
  client/src/Components/Dashboard/Book/index.jsx
  client/src/Components/Dashboard/DashboardBook/index.jsx
  client/src/Components/Dashboard/index.jsx
  client/src/Components/Login/index.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/index.jsx
  client/src/Contexts/adminContext.jsx
  client/src/Contexts/userContext.jsx
  client/src/Pages/Dashboard/index.jsx
  client/src/Pages/Profile/index.jsx
  client/src/Pages/index.jsx
  client/src/ProtectedRoute/AdminProtected.jsx
  client/src/ProtectedRoute/UserProtected.jsx
  client/src/ProtectedRoute/index.jsx
  client/src/index.jsx
Labels: Awaiting Review

#115 114 book day month
  server/controllers/book/getBookDay.ts
  server/controllers/book/getBookMonth.ts
  server/controllers/book/index.ts
  server/controllers/index.ts
  server/database/fakeData.sql
  server/queries/book/getBookDayQuery .ts
  server/queries/book/getBookMonthQuery.ts
  server/queries/book/index.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend

#108 Dashboard contact page
  client/src/Components/Dashboard/Contact/index.jsx
  client/src/Components/Dashboard/Contact/style.css
  client/src/Pages/Dashboard/index.jsx
  client/src/style/custom-antd.css
  server/controllers/contact/deleteContact.ts
  server/controllers/contact/index.ts
  server/controllers/contact/updateContactStatus.ts
  server/controllers/index.ts
  server/database/build.sql
  server/database/fakeData.sql
  server/queries/contact/deleteContactQuery.ts
  server/queries/contact/getContactsQuery.ts
  server/queries/contact/index.ts
  server/queries/contact/updateContactStatusQuery.ts
  server/queries/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Frontend

#118 create user profile page
  client/src/Components/Header/style.css
  client/src/Pages/Profile/Cover.jsx
  client/src/Pages/Profile/index.jsx
  client/src/Pages/Profile/style.css
Labels: Awaiting Review, Frontend

#119 Create Map In Book Container
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/src/App/index.jsx
  client/src/Assets/icons/location.svg
  client/src/Assets/images/marker.png
  client/src/Components/BookNow/BookContainer.jsx
  client/src/Components/BookNow/DateTimeChoice.jsx
  client/src/Components/BookNow/Summary.jsx
  client/src/Components/BookNow/UserInformation.jsx
  client/src/Components/Map/LocationMarker.jsx
  client/src/Components/Map/UseGeoLocation.jsx
  client/src/Components/Map/index.jsx
  client/src/Components/Map/osm-providers.js
  client/src/Components/Map/style.css
  client/src/Components/Register/index.jsx
  client/src/cities.json
  package-lock.json
  server/controllers/book/postBook.ts
  server/database/build.sql
  server/database/fakeData.sql
  server/queries/book/postBookQuery.ts
  server/validation/bookSchema.ts
  server/validation/signupSchema.ts
  test/index.test.ts
Labels: Awaiting Review, Frontend

#120 general dashboard
  client/package-lock.json
  client/package.json
  client/src/Components/Dashboard/General/BookStatus/StatusNumber/index.jsx
  client/src/Components/Dashboard/General/BookStatus/index.jsx
  client/src/Components/Dashboard/General/BookStatus/style.css
  client/src/Components/Dashboard/General/Chart/index.jsx
  client/src/Components/Dashboard/General/Chart/style.css
  client/src/Components/Dashboard/General/index.jsx
  server/database/fakeData.sql
  test/index.test.ts
Labels: Awaiting Review, Frontend

#123 update book
  server/controllers/book/index.ts
  server/controllers/book/updateBook.ts
  server/controllers/index.ts
  server/database/fakeData.sql
  server/queries/book/index.ts
  server/queries/book/updateBookQuery.ts
  server/queries/index.ts
  server/routes/index.ts
  server/validation/bookSchema.ts
  server/validation/index.ts
  server/validation/updateBookSchema.ts
  test/index.test.ts
Labels: Done

#126 Add Websocket
  client/package-lock.json
  client/package.json
  client/src/Components/Dashboard/Contact/index.jsx
  package-lock.json
  package.json
  server/app.ts
  server/controllers/contact/addContact.ts
  server/database/fakeData.sql
  server/index.ts
  test/index.test.ts
Labels: Awaiting Review

#127 services dashboard
  client/package-lock.json
  client/src/Components/BookNow/DateTimeChoice.jsx
  client/src/Components/Dashboard/Services/AddService/index.jsx
  client/src/Components/Dashboard/Services/AddService/style.css
  client/src/Components/Dashboard/Services/index.jsx
  client/src/Components/Dashboard/Services/style.css
  client/src/Pages/Dashboard/index.jsx
  client/src/Pages/Dashboard/style.css
  server/controllers/index.ts
  server/controllers/services/getServices.ts
  server/controllers/services/index.ts
  server/controllers/services/postService.ts
  server/controllers/services/putService.ts
  server/queries/contact/getContactsQuery.ts
  server/queries/index.ts
  server/queries/services/getServicesQuery.ts
  server/queries/services/index.ts
  server/routes/index.ts
  test/index.test.ts
Labels: Awaiting Review, Backend, Frontend

#129 some refactor
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/Dashboard/Contact/index.jsx
  client/src/Components/Dashboard/General/Chart/index.jsx
  client/src/Components/Dashboard/General/Chart/style.css
  client/src/Components/Dashboard/Services/AddService/add.tsx
  client/src/Components/Login/index.jsx
  client/src/Components/Navbar/index.jsx
  client/src/Components/Register/index.jsx
  client/src/Pages/Dashboard/index.jsx
  server/controllers/book/deleteBook.ts
  server/controllers/book/getBookDay.ts
  server/controllers/book/getBookMonth.ts
  server/controllers/book/postBook.ts
  server/controllers/book/updateBook.ts
  server/controllers/categories/archivedCategories.ts
  server/controllers/categories/postCategories.ts
  server/controllers/categories/putCategory.ts
  server/controllers/contact/addContact.ts
  server/controllers/contact/deleteContact.ts
  server/controllers/contact/updateContactStatus.ts
  server/controllers/logout/index.ts
  server/controllers/signin/index.ts
  server/controllers/signinAdmin/index.ts
  server/controllers/signup/index.ts
  test/index.test.ts
Labels: Awaiting Review

#125 Categories dashboard page
  .env.example
  client/.env.example
  client/src/App/app.css
  client/src/Components/Dashboard/Categories/FormModal.jsx
  client/src/Components/Dashboard/Categories/index.jsx
  client/src/Components/Dashboard/Categories/style.css
  client/src/Components/Dashboard/Contact/index.jsx
  server/queries/categories/getCategoriesQuery.ts
Labels: Awaiting Review, Frontend

#130 create book component
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/Components/BookNow/ServicesChoice.jsx
  client/src/Components/BookNow/ServicesCollapse.jsx
  client/src/Components/ContactUsForm/index.jsx
  client/src/Components/Dashboard/Categories/FormModal.jsx
  client/src/Components/Dashboard/Categories/index.jsx
  client/src/Components/Dashboard/Categories/style.css
  client/src/Components/Dashboard/Contact/index.jsx
  client/src/Components/Dashboard/DashboardBook/index.jsx
  client/src/Components/Dashboard/Services/AddService/add.tsx
  client/src/Components/Dashboard/Services/index.jsx
  client/src/Components/Dashboard/Services/style.css
  client/src/Components/Map/osm-providers.js
  client/src/Contexts/CategoriesContext.jsx
  client/src/Contexts/adminContext.jsx
  client/src/Contexts/userContext.jsx
  client/src/Pages/Dashboard/index.jsx
  client/src/ProtectedRoute/AdminProtected.jsx
  client/src/ProtectedRoute/UserProtected.jsx
  client/src/ProtectedRoute/index.jsx
  client/src/Utils/index.js
  package-lock.json
  package.json
  server/app.ts
  server/controllers/book/index.ts
  server/controllers/book/updateStatusBook.ts
  server/controllers/index.ts
  server/queries/book/getBooksQuery.ts
  server/queries/book/index.ts
  server/queries/book/updateStatusBookQuery.ts
  server/queries/contact/getContactsQuery.ts
  server/queries/index.ts
  server/routes/index.ts
  server/validation/bookStatusSchema.ts
  server/validation/index.ts
  test/index.test.ts
Labels: Awaiting Review

#135 fix websocket
  client/src/Components/BookNow/BookContainer.jsx
  client/src/Components/BookNow/UserInformation.jsx
  client/src/Components/Dashboard/Contact/index.jsx
  client/src/Components/Dashboard/DashboardBook/index.jsx
  client/src/Components/Dashboard/General/Chart/index.jsx
  client/src/Components/Dashboard/General/Chart/style.css
  client/src/Components/Map/LocationMarker.jsx
  client/src/Components/Map/index.jsx
  client/src/Contexts/userContext.jsx
  server/app.ts
  server/controllers/book/postBook.ts
  server/controllers/contact/addContact.ts
  server/queries/book/getBookDayQuery .ts
  server/queries/book/getBookMonthQuery.ts
Labels: Awaiting Review

#137 Send email
  client/src/Components/BookNow/BookContainer.jsx
  client/src/Components/BookNow/Summary.jsx
  client/src/Components/BookNow/style.css
  client/src/Components/CustomTitle/index.jsx
  client/src/Components/CustomTitle/style.css
  client/src/Components/Footer/style.css
  client/src/Components/Navbar/RightMenu.jsx
  client/src/Components/Navbar/navbar.css
  client/src/Components/WhatTheySay/style.css
  client/src/Pages/Dashboard/style.css
  package-lock.json
  package.json
  server/controllers/book/updateStatusBook.ts
  server/queries/index.ts
  server/queries/user/getEmailQuery.ts
  server/queries/user/index.ts
  server/routes/index.ts
  server/utils/emailTemplates/accepetBook.ts
  server/utils/emailTemplates/declineBook.ts
  server/utils/emailTemplates/index.ts
  server/utils/index.ts
  tsconfig.json
Labels: Awaiting Review

#132 Fix pages style
  client/src/Components/BookNow/BookContainer.jsx
  client/src/Components/BookNow/Summary.jsx
  client/src/Components/BookNow/style.css
  client/src/Components/CustomTitle/index.jsx
  client/src/Components/CustomTitle/style.css
  client/src/Components/Footer/style.css
  client/src/Components/Navbar/RightMenu.jsx
  client/src/Components/Navbar/navbar.css
  client/src/Components/WhatTheySay/style.css
  client/src/Pages/Dashboard/style.css
  package-lock.json
  package.json
Labels: In Progress

#139 README
  README.md
Labels: Awaiting Review

#141 fix header button
  .env.example
  client/.env.example
  client/src/Components/Dashboard/Categories/FormModal.jsx
  client/src/Components/Dashboard/Services/index.jsx
  client/src/Components/Header/index.jsx
Labels: Awaiting Review
